#!/bin/bash
php migrate_run.php

php add_user.php vugluskr admin 123456
php add_user.php "Петров Максим" manager 654321
php add_user.php "Двинских Андрей Станиславович" rat 123
php add_user.php "Зайцев Сергей Валерьевич" rat 123
php add_user.php "Константинов Евгений Алексеевич" rat 123

php add_user.php "Мальцев Андрей Александрович" rat 123
php add_user.php "Молчанов Павел Юрьевич  " rat 123
php add_user.php "Ротяков Евгений Николаевич" rat 123
php add_user.php "Ротяков Евгений Николаевич" rat 123
php add_user.php "Тюкавин Сергей Геннадьевич	Слесарь" rat 123
php add_user.php "Уфимцев Максим	Слесарь" rat 123
php add_user.php "Чермашенцев Алексей Борисович	Мастер" rat 123

php add_customer.php "Шлакоблок Петр Петрович" "+792512345687"
php add_customer.php "Валенок Антон Семенович" "+792512345589"
php add_customer.php "Петр Первый" "+795812345589"
php add_customer.php "Василий Олегович Вассерманович" "+795815355589"

php add_customer_car.php Car1 1 vin01-123 123
php add_customer_car.php Car2 2 vin02-456 456
php add_customer_car.php Car3 3 vin03-789 789
php add_customer_car.php Car4 4 vin04-012 012
php add_customer_car.php Car5 5 vin05-345 345
php add_customer_car.php Car6 6 vin06-678 678
php add_customer_car.php Car7 7 vin07-901 901
php add_customer_car.php Car8 8 vin08-234 234

php add_repair_post.php "Пост1"
php add_repair_type.php 1 "2013 Замена блока предохранителей"
php add_repair_type.php 1 "Балансировка колеса"
php add_repair_type.php 1 "Бортовка колеса"
php add_repair_type.php 1 "Диагностика автоэлектрики автомобиля"
php add_repair_type.php 1 "Диагностика двигателя"
php add_repair_type.php 1 "Диагностика на вибростенде"
php add_repair_type.php 1 "Забортовка колеса"
php add_repair_type.php 1 "Замена амортизаторов (иномарки)"
php add_repair_type.php 1 "Замена амортизаторов (отечеств)"
php add_repair_type.php 1 "Замена амортизаторов перед (отечеств)"
php add_repair_type.php 1 "Замена антифриза"
php add_repair_type.php 1 "Замена барабана (тормозного)"
php add_repair_type.php 1 "Замена бачка (расширительного)"
php add_repair_type.php 1 "Замена блока предохранителей"
php add_repair_type.php 1 "Замена Вакуумный усилитель"
php add_repair_type.php 1 "Замена Вал карданный рулевой УАЗ"
php add_repair_type.php 1 "Замена вентиля"
php add_repair_type.php 1 "Замена вкладышей (коренных)"
php add_repair_type.php 1 "Замена вкладышей (шатунных)"
php add_repair_type.php 1 "Замена втулок задней балки"
php add_repair_type.php 1 "Замена втулок рессорных"
php add_repair_type.php 1 "Замена втулок стабилизатора"
php add_repair_type.php 1 "Замена Втулок стабилизатора УАЗ"
php add_repair_type.php 1 "Замена генератора"
php add_repair_type.php 1 "Замена глушителя"
php add_repair_type.php 1 "Замена гранаты (шрус)"
php add_repair_type.php 1 "Замена ГРМ (ремни, ролики)"
php add_repair_type.php 1 "Замена датчика (все остальные)"
php add_repair_type.php 1 "Замена датчика положения дросельн. заслонки"
php add_repair_type.php 1 "Замена датчика положения распредвала"
php add_repair_type.php 1 "Замена датчика холостого хода"
php add_repair_type.php 1 "Замена дверных ручек"
php add_repair_type.php 1 "Замена заднего стабилизатора"
php add_repair_type.php 1 "Замена замка двери"
php add_repair_type.php 1 "Замена замка зажигания"
php add_repair_type.php 1 "Замена кардана (заднего) УАЗ"
php add_repair_type.php 1 "Замена кардана (переднего) УАЗ"
php add_repair_type.php 1 "Замена катушки зажигания"
php add_repair_type.php 1 "Замена клаппанов"
php add_repair_type.php 1 "Замена коллектора (выпускного)"
php add_repair_type.php 1 "Замена крестовины"
php add_repair_type.php 1 "Замена крестовины КПП"
php add_repair_type.php 1 "Замена кронштейна растяжки (краб)"
php add_repair_type.php 1 "замена масла в мостах"
php add_repair_type.php 1 "Замена масла в разд. кор."
php add_repair_type.php 1 "Замена масла ГУР"
php add_repair_type.php 1 "Замена масла ДВС"
php add_repair_type.php 1 "Замена масла КПП"
php add_repair_type.php 1 "Замена масла трансмисии"
php add_repair_type.php 1 "Замена мотора отопителя"
php add_repair_type.php 1 "Замена наконечников рулевых"
php add_repair_type.php 1 "Замена насоса маслянного"
php add_repair_type.php 1 "Замена опор стоек (перед)"
php add_repair_type.php 1 "Замена патрубка системы охлаждения"
php add_repair_type.php 1 "Замена платы фонаря (задн)"
php add_repair_type.php 1 "Замена подушки двигателя"
php add_repair_type.php 1 "Замена подшипника генератора (бол.)"
php add_repair_type.php 1 "Замена подшипника генератора (мал.)"
php add_repair_type.php 1 "Замена подшипника ступицы (задн.)"
php add_repair_type.php 1 "Замена подшипника ступицы (передн.)"
php add_repair_type.php 1 "Замена полуоси"
php add_repair_type.php 1 "Замена помпы (водяной насос)"
php add_repair_type.php 1 "Замена поршневой группы"
php add_repair_type.php 1 "Замена привода"
php add_repair_type.php 1 "Замена провода"
php add_repair_type.php 1 "Замена прокладки глушителя"
php add_repair_type.php 1 "Замена прокладки смотрового окна штанги"
php add_repair_type.php 1 "Замена пыльника гранаты (наружной)"
php add_repair_type.php 1 "Замена радиатора"
php add_repair_type.php 1 "Замена реактивных тяг"
php add_repair_type.php 1 "Замена регулятора тормозных сил"
php add_repair_type.php 1 "Замена резистора печки"
php add_repair_type.php 1 "Замена резонатора"
php add_repair_type.php 1 "Замена ремня / НЕ БРАТЬ"
php add_repair_type.php 1 "Замена ремня генератора"
php add_repair_type.php 1 "Замена ремня и роликов"
php add_repair_type.php 1 "Замена ремня ручейкового"
php add_repair_type.php 1 "Замена реостат переключателя печки"
php add_repair_type.php 1 "Замена ролика ГРМ (натяжного)"
php add_repair_type.php 1 "Замена рулевого кардана"
php add_repair_type.php 1 "Замена рулевой рейки"
php add_repair_type.php 1 "Замена рулевой трапеции"
php add_repair_type.php 1 "Замена рулевой тяги"
php add_repair_type.php 1 "Замена ручки двери"
php add_repair_type.php 1 "Замена рычага переключения передач"
php add_repair_type.php 1 "Замена рычага(нижнего)"
php add_repair_type.php 1 "Замена рычага(нижнего) косточка"
php add_repair_type.php 1 "Замена сайлентблоков"
php add_repair_type.php 1 "Замена сайлентблоков (отечеств)"
php add_repair_type.php 1 "Замена сайлентблоков перед (иномарки)"
php add_repair_type.php 1 "Замена сайлентблоков продольных тяг"
php add_repair_type.php 1 "Замена сальника коленвала (переднего)"
php add_repair_type.php 1 "Замена сальника КПП"
php add_repair_type.php 1 "Замена сальника полуоси"
php add_repair_type.php 1 "Замена сальника редуктора заднего моста"
php add_repair_type.php 1 "Замена сальников клаппанов"
php add_repair_type.php 1 "Замена свечей зажигания"
php add_repair_type.php 1 "Замена стартера"
php add_repair_type.php 1 "Замена стекла лобового"
php add_repair_type.php 1 "Замена стоек стабилизатора (линьки)"
php add_repair_type.php 1 "Замена ступицы (в сборе)"
php add_repair_type.php 1 "Замена сцепления"
php add_repair_type.php 1 "Замена термостата"
php add_repair_type.php 1 "Замена тормозного суппорта"
php add_repair_type.php 1 "Замена тормозной жидкости"
php add_repair_type.php 1 "Замена тормозных дисков"
php add_repair_type.php 1 "Замена тормозных колодок(дисковые)"
php add_repair_type.php 1 "Замена тормозных колодок(задних)"
php add_repair_type.php 1 "Замена тормозных колодок(пердних)"
php add_repair_type.php 1 "Замена тосола"
php add_repair_type.php 1 "Замена траверса КПП"
php add_repair_type.php 1 "Замена тросов ручного тормоза"
php add_repair_type.php 1 "Замена тяги в сборе (поперечная) УАЗ"
php add_repair_type.php 1 "Замена фильтра (воздушного)"
php add_repair_type.php 1 "Замена фильтра (салон)"
php add_repair_type.php 1 "Замена фильтра (тон.очистки)"
php add_repair_type.php 1 "Замена фильтра (топливного)"
php add_repair_type.php 1 "Замена фильтра АКПП"
php add_repair_type.php 1 "Замена фильтров"
php add_repair_type.php 1 "Замена форсунок"
php add_repair_type.php 1 "Замена цилиндра сцепления (главный)"
php add_repair_type.php 1 "Замена цилиндра сцепления (рабочий)"
php add_repair_type.php 1 "Замена цилиндра тормозного (главного)"
php add_repair_type.php 1 "Замена цилиндра тормозного (заднего)"
php add_repair_type.php 1 "Замена шаровой опоры"
php add_repair_type.php 1 "Замена шестерни зажигания (ведущей)"
php add_repair_type.php 1 "Замена шестерни распредвала"
php add_repair_type.php 1 "Замена шкворней"
php add_repair_type.php 1 "Замена шланга топливного"
php add_repair_type.php 1 "Замена шланга тормозного"
php add_repair_type.php 1 "Заправка кондиционера"
php add_repair_type.php 1 "Мойка автомобиля"
php add_repair_type.php 1 "Мойка блока двигателя"
php add_repair_type.php 1 "Мойка головки двигателя"
php add_repair_type.php 1 "Мойка колеса"
php add_repair_type.php 1 "Набивка коленвала"
php add_repair_type.php 1 "Осмотр ходовой"
php add_repair_type.php 1 "Перебортовка колеса"
php add_repair_type.php 1 "Подкачка колеса"
php add_repair_type.php 1 "Правка диска колеса"
php add_repair_type.php 1 "Притирка клаппанов"
php add_repair_type.php 1 "Проверка клаппанов"
php add_repair_type.php 1 "Промазка колеса"
php add_repair_type.php 1 "Промазка колеса герметиком"
php add_repair_type.php 1 "Разборка/Сборка ДВС"
php add_repair_type.php 1 "Разбортовка колеса"
php add_repair_type.php 1 "Развал-схождения"
php add_repair_type.php 1 "Райбирование направляющих клаппанов"
php add_repair_type.php 1 "Регулеровка ручного тормоза"
php add_repair_type.php 1 "Регулировка"
php add_repair_type.php 1 "Регулировка клапанов (в диагностике)"
php add_repair_type.php 1 "Регулировка рулевой рейки"
php add_repair_type.php 1 "Ремонт блока предохранителей"
php add_repair_type.php 1 "Ремонт генератора"
php add_repair_type.php 1 "Ремонт головки блока"
php add_repair_type.php 1 "Ремонт замка (центрального)"
php add_repair_type.php 1 "Ремонт камеры"
php add_repair_type.php 1 "Ремонт кронштейна крепления рулевой рейки"
php add_repair_type.php 1 "Ремонт МКПП (коробки передач)"
php add_repair_type.php 1 "Ремонт стеклоподъемника"
php add_repair_type.php 1 "Ремонт шины"
php add_repair_type.php 1 "Ремонт шины грибком"
php add_repair_type.php 1 "Ремонт шины пластырем R-19"
php add_repair_type.php 1 "Ремонт электропроводки"
php add_repair_type.php 1 "Сварка защиты картера"
php add_repair_type.php 1 "Снятие/Установка головки блока"
php add_repair_type.php 1 "Снятие/Установка ДВС"
php add_repair_type.php 1 "Снятие/Установка колеса"
php add_repair_type.php 1 "Срез болтов"
php add_repair_type.php 1 "Установка пластырей"
php add_repair_type.php 1 "Установка руля"
php add_repair_type.php 1 "Чистка диска"
php add_repair_type.php 1 "Чистка инжектора"
php add_repair_type.php 1 "Чистка регулятора холостого хода"
php add_repair_type.php 1 "Чистка форсунок"
php add_repair_type.php 1 "Шлифовка головки блока"
php add_repair_type.php 1 "Шлифовка коленвала"
php add_repair_type.php 1 "Шлифовка кольца осевого хождения коленчатого вала"
php add_repair_type.php 1 "Шприцевание кардана (замена смазки) 1 шт?"



php add_repair_post.php "Пост2"
php add_repair_type.php 2 "2013 Замена блока предохранителей"
php add_repair_type.php 2 "Балансировка колеса"
php add_repair_type.php 2 "Бортовка колеса"
php add_repair_type.php 2 "Диагностика автоэлектрики автомобиля"
php add_repair_type.php 2 "Диагностика двигателя"
php add_repair_type.php 2 "Диагностика на вибростенде"
php add_repair_type.php 2 "Забортовка колеса"
php add_repair_type.php 2 "Замена амортизаторов (иномарки)"
php add_repair_type.php 2 "Замена амортизаторов (отечеств)"
php add_repair_type.php 2 "Замена амортизаторов перед (отечеств)"
php add_repair_type.php 2 "Замена антифриза"
php add_repair_type.php 2 "Замена барабана (тормозного)"
php add_repair_type.php 2 "Замена бачка (расширительного)"
php add_repair_type.php 2 "Замена блока предохранителей"
php add_repair_type.php 2 "Замена Вакуумный усилитель"
php add_repair_type.php 2 "Замена Вал карданный рулевой УАЗ"
php add_repair_type.php 2 "Замена вентиля"
php add_repair_type.php 2 "Замена вкладышей (коренных)"
php add_repair_type.php 2 "Замена вкладышей (шатунных)"
php add_repair_type.php 2 "Замена втулок задней балки"
php add_repair_type.php 2 "Замена втулок рессорных"
php add_repair_type.php 2 "Замена втулок стабилизатора"
php add_repair_type.php 2 "Замена Втулок стабилизатора УАЗ"
php add_repair_type.php 2 "Замена генератора"
php add_repair_type.php 2 "Замена глушителя"
php add_repair_type.php 2 "Замена гранаты (шрус)"
php add_repair_type.php 2 "Замена ГРМ (ремни, ролики)"
php add_repair_type.php 2 "Замена датчика (все остальные)"
php add_repair_type.php 2 "Замена датчика положения дросельн. заслонки"
php add_repair_type.php 2 "Замена датчика положения распредвала"
php add_repair_type.php 2 "Замена датчика холостого хода"
php add_repair_type.php 2 "Замена дверных ручек"
php add_repair_type.php 2 "Замена заднего стабилизатора"
php add_repair_type.php 2 "Замена замка двери"
php add_repair_type.php 2 "Замена замка зажигания"
php add_repair_type.php 2 "Замена кардана (заднего) УАЗ"
php add_repair_type.php 2 "Замена кардана (переднего) УАЗ"
php add_repair_type.php 2 "Замена катушки зажигания"
php add_repair_type.php 2 "Замена клаппанов"
php add_repair_type.php 2 "Замена коллектора (выпускного)"
php add_repair_type.php 2 "Замена крестовины"
php add_repair_type.php 2 "Замена крестовины КПП"
php add_repair_type.php 2 "Замена кронштейна растяжки (краб)"
php add_repair_type.php 2 "замена масла в мостах"
php add_repair_type.php 2 "Замена масла в разд. кор."
php add_repair_type.php 2 "Замена масла ГУР"
php add_repair_type.php 2 "Замена масла ДВС"
php add_repair_type.php 2 "Замена масла КПП"
php add_repair_type.php 2 "Замена масла трансмисии"
php add_repair_type.php 2 "Замена мотора отопителя"
php add_repair_type.php 2 "Замена наконечников рулевых"
php add_repair_type.php 2 "Замена насоса маслянного"
php add_repair_type.php 2 "Замена опор стоек (перед)"
php add_repair_type.php 2 "Замена патрубка системы охлаждения"
php add_repair_type.php 2 "Замена платы фонаря (задн)"
php add_repair_type.php 2 "Замена подушки двигателя"
php add_repair_type.php 2 "Замена подшипника генератора (бол.)"
php add_repair_type.php 2 "Замена подшипника генератора (мал.)"
php add_repair_type.php 2 "Замена подшипника ступицы (задн.)"
php add_repair_type.php 2 "Замена подшипника ступицы (передн.)"
php add_repair_type.php 2 "Замена полуоси"
php add_repair_type.php 2 "Замена помпы (водяной насос)"
php add_repair_type.php 2 "Замена поршневой группы"
php add_repair_type.php 2 "Замена привода"
php add_repair_type.php 2 "Замена провода"
php add_repair_type.php 2 "Замена прокладки глушителя"
php add_repair_type.php 2 "Замена прокладки смотрового окна штанги"
php add_repair_type.php 2 "Замена пыльника гранаты (наружной)"
php add_repair_type.php 2 "Замена радиатора"
php add_repair_type.php 2 "Замена реактивных тяг"
php add_repair_type.php 2 "Замена регулятора тормозных сил"
php add_repair_type.php 2 "Замена резистора печки"
php add_repair_type.php 2 "Замена резонатора"
php add_repair_type.php 2 "Замена ремня / НЕ БРАТЬ"
php add_repair_type.php 2 "Замена ремня генератора"
php add_repair_type.php 2 "Замена ремня и роликов"
php add_repair_type.php 2 "Замена ремня ручейкового"
php add_repair_type.php 2 "Замена реостат переключателя печки"
php add_repair_type.php 2 "Замена ролика ГРМ (натяжного)"
php add_repair_type.php 2 "Замена рулевого кардана"
php add_repair_type.php 2 "Замена рулевой рейки"
php add_repair_type.php 2 "Замена рулевой трапеции"
php add_repair_type.php 2 "Замена рулевой тяги"
php add_repair_type.php 2 "Замена ручки двери"
php add_repair_type.php 2 "Замена рычага переключения передач"
php add_repair_type.php 2 "Замена рычага(нижнего)"
php add_repair_type.php 2 "Замена рычага(нижнего) косточка"
php add_repair_type.php 2 "Замена сайлентблоков"
php add_repair_type.php 2 "Замена сайлентблоков (отечеств)"
php add_repair_type.php 2 "Замена сайлентблоков перед (иномарки)"
php add_repair_type.php 2 "Замена сайлентблоков продольных тяг"
php add_repair_type.php 2 "Замена сальника коленвала (переднего)"
php add_repair_type.php 2 "Замена сальника КПП"
php add_repair_type.php 2 "Замена сальника полуоси"
php add_repair_type.php 2 "Замена сальника редуктора заднего моста"
php add_repair_type.php 2 "Замена сальников клаппанов"
php add_repair_type.php 2 "Замена свечей зажигания"
php add_repair_type.php 2 "Замена стартера"
php add_repair_type.php 2 "Замена стекла лобового"
php add_repair_type.php 2 "Замена стоек стабилизатора (линьки)"
php add_repair_type.php 2 "Замена ступицы (в сборе)"
php add_repair_type.php 2 "Замена сцепления"
php add_repair_type.php 2 "Замена термостата"
php add_repair_type.php 2 "Замена тормозного суппорта"
php add_repair_type.php 2 "Замена тормозной жидкости"
php add_repair_type.php 2 "Замена тормозных дисков"
php add_repair_type.php 2 "Замена тормозных колодок(дисковые)"
php add_repair_type.php 2 "Замена тормозных колодок(задних)"
php add_repair_type.php 2 "Замена тормозных колодок(пердних)"
php add_repair_type.php 2 "Замена тосола"
php add_repair_type.php 2 "Замена траверса КПП"
php add_repair_type.php 2 "Замена тросов ручного тормоза"
php add_repair_type.php 2 "Замена тяги в сборе (поперечная) УАЗ"
php add_repair_type.php 2 "Замена фильтра (воздушного)"
php add_repair_type.php 2 "Замена фильтра (салон)"
php add_repair_type.php 2 "Замена фильтра (тон.очистки)"
php add_repair_type.php 2 "Замена фильтра (топливного)"
php add_repair_type.php 2 "Замена фильтра АКПП"
php add_repair_type.php 2 "Замена фильтров"
php add_repair_type.php 2 "Замена форсунок"
php add_repair_type.php 2 "Замена цилиндра сцепления (главный)"
php add_repair_type.php 2 "Замена цилиндра сцепления (рабочий)"
php add_repair_type.php 2 "Замена цилиндра тормозного (главного)"
php add_repair_type.php 2 "Замена цилиндра тормозного (заднего)"
php add_repair_type.php 2 "Замена шаровой опоры"
php add_repair_type.php 2 "Замена шестерни зажигания (ведущей)"
php add_repair_type.php 2 "Замена шестерни распредвала"
php add_repair_type.php 2 "Замена шкворней"
php add_repair_type.php 2 "Замена шланга топливного"
php add_repair_type.php 2 "Замена шланга тормозного"
php add_repair_type.php 2 "Заправка кондиционера"
php add_repair_type.php 2 "Мойка автомобиля"
php add_repair_type.php 2 "Мойка блока двигателя"
php add_repair_type.php 2 "Мойка головки двигателя"
php add_repair_type.php 2 "Мойка колеса"
php add_repair_type.php 2 "Набивка коленвала"
php add_repair_type.php 2 "Осмотр ходовой"
php add_repair_type.php 2 "Перебортовка колеса"
php add_repair_type.php 2 "Подкачка колеса"
php add_repair_type.php 2 "Правка диска колеса"
php add_repair_type.php 2 "Притирка клаппанов"
php add_repair_type.php 2 "Проверка клаппанов"
php add_repair_type.php 2 "Промазка колеса"
php add_repair_type.php 2 "Промазка колеса герметиком"
php add_repair_type.php 2 "Разборка/Сборка ДВС"
php add_repair_type.php 2 "Разбортовка колеса"
php add_repair_type.php 2 "Развал-схождения"
php add_repair_type.php 2 "Райбирование направляющих клаппанов"
php add_repair_type.php 2 "Регулеровка ручного тормоза"
php add_repair_type.php 2 "Регулировка"
php add_repair_type.php 2 "Регулировка клапанов (в диагностике)"
php add_repair_type.php 2 "Регулировка рулевой рейки"
php add_repair_type.php 2 "Ремонт блока предохранителей"
php add_repair_type.php 2 "Ремонт генератора"
php add_repair_type.php 2 "Ремонт головки блока"
php add_repair_type.php 2 "Ремонт замка (центрального)"
php add_repair_type.php 2 "Ремонт камеры"
php add_repair_type.php 2 "Ремонт кронштейна крепления рулевой рейки"
php add_repair_type.php 2 "Ремонт МКПП (коробки передач)"
php add_repair_type.php 2 "Ремонт стеклоподъемника"
php add_repair_type.php 2 "Ремонт шины"
php add_repair_type.php 2 "Ремонт шины грибком"
php add_repair_type.php 2 "Ремонт шины пластырем R-19"
php add_repair_type.php 2 "Ремонт электропроводки"
php add_repair_type.php 2 "Сварка защиты картера"
php add_repair_type.php 2 "Снятие/Установка головки блока"
php add_repair_type.php 2 "Снятие/Установка ДВС"
php add_repair_type.php 2 "Снятие/Установка колеса"
php add_repair_type.php 2 "Срез болтов"
php add_repair_type.php 2 "Установка пластырей"
php add_repair_type.php 2 "Установка руля"
php add_repair_type.php 2 "Чистка диска"
php add_repair_type.php 2 "Чистка инжектора"
php add_repair_type.php 2 "Чистка регулятора холостого хода"
php add_repair_type.php 2 "Чистка форсунок"
php add_repair_type.php 2 "Шлифовка головки блока"
php add_repair_type.php 2 "Шлифовка коленвала"
php add_repair_type.php 2 "Шлифовка кольца осевого хождения коленчатого вала"
php add_repair_type.php 2 "Шприцевание кардана (замена смазки) 1 шт?"

php add_repair_post.php "Пост3"
php add_repair_type.php 3 "2013 Замена блока предохранителей"
php add_repair_type.php 3 "Балансировка колеса"
php add_repair_type.php 3 "Бортовка колеса"
php add_repair_type.php 3 "Диагностика автоэлектрики автомобиля"
php add_repair_type.php 3 "Диагностика двигателя"
php add_repair_type.php 3 "Диагностика на вибростенде"
php add_repair_type.php 3 "Забортовка колеса"
php add_repair_type.php 3 "Замена амортизаторов (иномарки)"
php add_repair_type.php 3 "Замена амортизаторов (отечеств)"
php add_repair_type.php 3 "Замена амортизаторов перед (отечеств)"
php add_repair_type.php 3 "Замена антифриза"
php add_repair_type.php 3 "Замена барабана (тормозного)"
php add_repair_type.php 3 "Замена бачка (расширительного)"
php add_repair_type.php 3 "Замена блока предохранителей"
php add_repair_type.php 3 "Замена Вакуумный усилитель"
php add_repair_type.php 3 "Замена Вал карданный рулевой УАЗ"
php add_repair_type.php 3 "Замена вентиля"
php add_repair_type.php 3 "Замена вкладышей (коренных)"
php add_repair_type.php 3 "Замена вкладышей (шатунных)"
php add_repair_type.php 3 "Замена втулок задней балки"
php add_repair_type.php 3 "Замена втулок рессорных"
php add_repair_type.php 3 "Замена втулок стабилизатора"
php add_repair_type.php 3 "Замена Втулок стабилизатора УАЗ"
php add_repair_type.php 3 "Замена генератора"
php add_repair_type.php 3 "Замена глушителя"
php add_repair_type.php 3 "Замена гранаты (шрус)"
php add_repair_type.php 3 "Замена ГРМ (ремни, ролики)"
php add_repair_type.php 3 "Замена датчика (все остальные)"
php add_repair_type.php 3 "Замена датчика положения дросельн. заслонки"
php add_repair_type.php 3 "Замена датчика положения распредвала"
php add_repair_type.php 3 "Замена датчика холостого хода"
php add_repair_type.php 3 "Замена дверных ручек"
php add_repair_type.php 3 "Замена заднего стабилизатора"
php add_repair_type.php 3 "Замена замка двери"
php add_repair_type.php 3 "Замена замка зажигания"
php add_repair_type.php 3 "Замена кардана (заднего) УАЗ"
php add_repair_type.php 3 "Замена кардана (переднего) УАЗ"
php add_repair_type.php 3 "Замена катушки зажигания"
php add_repair_type.php 3 "Замена клаппанов"
php add_repair_type.php 3 "Замена коллектора (выпускного)"
php add_repair_type.php 3 "Замена крестовины"
php add_repair_type.php 3 "Замена крестовины КПП"
php add_repair_type.php 3 "Замена кронштейна растяжки (краб)"
php add_repair_type.php 3 "замена масла в мостах"
php add_repair_type.php 3 "Замена масла в разд. кор."
php add_repair_type.php 3 "Замена масла ГУР"
php add_repair_type.php 3 "Замена масла ДВС"
php add_repair_type.php 3 "Замена масла КПП"
php add_repair_type.php 3 "Замена масла трансмисии"
php add_repair_type.php 3 "Замена мотора отопителя"
php add_repair_type.php 3 "Замена наконечников рулевых"
php add_repair_type.php 3 "Замена насоса маслянного"
php add_repair_type.php 3 "Замена опор стоек (перед)"
php add_repair_type.php 3 "Замена патрубка системы охлаждения"
php add_repair_type.php 3 "Замена платы фонаря (задн)"
php add_repair_type.php 3 "Замена подушки двигателя"
php add_repair_type.php 3 "Замена подшипника генератора (бол.)"
php add_repair_type.php 3 "Замена подшипника генератора (мал.)"
php add_repair_type.php 3 "Замена подшипника ступицы (задн.)"
php add_repair_type.php 3 "Замена подшипника ступицы (передн.)"
php add_repair_type.php 3 "Замена полуоси"
php add_repair_type.php 3 "Замена помпы (водяной насос)"
php add_repair_type.php 3 "Замена поршневой группы"
php add_repair_type.php 3 "Замена привода"
php add_repair_type.php 3 "Замена провода"
php add_repair_type.php 3 "Замена прокладки глушителя"
php add_repair_type.php 3 "Замена прокладки смотрового окна штанги"
php add_repair_type.php 3 "Замена пыльника гранаты (наружной)"
php add_repair_type.php 3 "Замена радиатора"
php add_repair_type.php 3 "Замена реактивных тяг"
php add_repair_type.php 3 "Замена регулятора тормозных сил"
php add_repair_type.php 3 "Замена резистора печки"
php add_repair_type.php 3 "Замена резонатора"
php add_repair_type.php 3 "Замена ремня / НЕ БРАТЬ"
php add_repair_type.php 3 "Замена ремня генератора"
php add_repair_type.php 3 "Замена ремня и роликов"
php add_repair_type.php 3 "Замена ремня ручейкового"
php add_repair_type.php 3 "Замена реостат переключателя печки"
php add_repair_type.php 3 "Замена ролика ГРМ (натяжного)"
php add_repair_type.php 3 "Замена рулевого кардана"
php add_repair_type.php 3 "Замена рулевой рейки"
php add_repair_type.php 3 "Замена рулевой трапеции"
php add_repair_type.php 3 "Замена рулевой тяги"
php add_repair_type.php 3 "Замена ручки двери"
php add_repair_type.php 3 "Замена рычага переключения передач"
php add_repair_type.php 3 "Замена рычага(нижнего)"
php add_repair_type.php 3 "Замена рычага(нижнего) косточка"
php add_repair_type.php 3 "Замена сайлентблоков"
php add_repair_type.php 3 "Замена сайлентблоков (отечеств)"
php add_repair_type.php 3 "Замена сайлентблоков перед (иномарки)"
php add_repair_type.php 3 "Замена сайлентблоков продольных тяг"
php add_repair_type.php 3 "Замена сальника коленвала (переднего)"
php add_repair_type.php 3 "Замена сальника КПП"
php add_repair_type.php 3 "Замена сальника полуоси"
php add_repair_type.php 3 "Замена сальника редуктора заднего моста"
php add_repair_type.php 3 "Замена сальников клаппанов"
php add_repair_type.php 3 "Замена свечей зажигания"
php add_repair_type.php 3 "Замена стартера"
php add_repair_type.php 3 "Замена стекла лобового"
php add_repair_type.php 3 "Замена стоек стабилизатора (линьки)"
php add_repair_type.php 3 "Замена ступицы (в сборе)"
php add_repair_type.php 3 "Замена сцепления"
php add_repair_type.php 3 "Замена термостата"
php add_repair_type.php 3 "Замена тормозного суппорта"
php add_repair_type.php 3 "Замена тормозной жидкости"
php add_repair_type.php 3 "Замена тормозных дисков"
php add_repair_type.php 3 "Замена тормозных колодок(дисковые)"
php add_repair_type.php 3 "Замена тормозных колодок(задних)"
php add_repair_type.php 3 "Замена тормозных колодок(пердних)"
php add_repair_type.php 3 "Замена тосола"
php add_repair_type.php 3 "Замена траверса КПП"
php add_repair_type.php 3 "Замена тросов ручного тормоза"
php add_repair_type.php 3 "Замена тяги в сборе (поперечная) УАЗ"
php add_repair_type.php 3 "Замена фильтра (воздушного)"
php add_repair_type.php 3 "Замена фильтра (салон)"
php add_repair_type.php 3 "Замена фильтра (тон.очистки)"
php add_repair_type.php 3 "Замена фильтра (топливного)"
php add_repair_type.php 3 "Замена фильтра АКПП"
php add_repair_type.php 3 "Замена фильтров"
php add_repair_type.php 3 "Замена форсунок"
php add_repair_type.php 3 "Замена цилиндра сцепления (главный)"
php add_repair_type.php 3 "Замена цилиндра сцепления (рабочий)"
php add_repair_type.php 3 "Замена цилиндра тормозного (главного)"
php add_repair_type.php 3 "Замена цилиндра тормозного (заднего)"
php add_repair_type.php 3 "Замена шаровой опоры"
php add_repair_type.php 3 "Замена шестерни зажигания (ведущей)"
php add_repair_type.php 3 "Замена шестерни распредвала"
php add_repair_type.php 3 "Замена шкворней"
php add_repair_type.php 3 "Замена шланга топливного"
php add_repair_type.php 3 "Замена шланга тормозного"
php add_repair_type.php 3 "Заправка кондиционера"
php add_repair_type.php 3 "Мойка автомобиля"
php add_repair_type.php 3 "Мойка блока двигателя"
php add_repair_type.php 3 "Мойка головки двигателя"
php add_repair_type.php 3 "Мойка колеса"
php add_repair_type.php 3 "Набивка коленвала"
php add_repair_type.php 3 "Осмотр ходовой"
php add_repair_type.php 3 "Перебортовка колеса"
php add_repair_type.php 3 "Подкачка колеса"
php add_repair_type.php 3 "Правка диска колеса"
php add_repair_type.php 3 "Притирка клаппанов"
php add_repair_type.php 3 "Проверка клаппанов"
php add_repair_type.php 3 "Промазка колеса"
php add_repair_type.php 3 "Промазка колеса герметиком"
php add_repair_type.php 3 "Разборка/Сборка ДВС"
php add_repair_type.php 3 "Разбортовка колеса"
php add_repair_type.php 3 "Развал-схождения"
php add_repair_type.php 3 "Райбирование направляющих клаппанов"
php add_repair_type.php 3 "Регулеровка ручного тормоза"
php add_repair_type.php 3 "Регулировка"
php add_repair_type.php 3 "Регулировка клапанов (в диагностике)"
php add_repair_type.php 3 "Регулировка рулевой рейки"
php add_repair_type.php 3 "Ремонт блока предохранителей"
php add_repair_type.php 3 "Ремонт генератора"
php add_repair_type.php 3 "Ремонт головки блока"
php add_repair_type.php 3 "Ремонт замка (центрального)"
php add_repair_type.php 3 "Ремонт камеры"
php add_repair_type.php 3 "Ремонт кронштейна крепления рулевой рейки"
php add_repair_type.php 3 "Ремонт МКПП (коробки передач)"
php add_repair_type.php 3 "Ремонт стеклоподъемника"
php add_repair_type.php 3 "Ремонт шины"
php add_repair_type.php 3 "Ремонт шины грибком"
php add_repair_type.php 3 "Ремонт шины пластырем R-19"
php add_repair_type.php 3 "Ремонт электропроводки"
php add_repair_type.php 3 "Сварка защиты картера"
php add_repair_type.php 3 "Снятие/Установка головки блока"
php add_repair_type.php 3 "Снятие/Установка ДВС"
php add_repair_type.php 3 "Снятие/Установка колеса"
php add_repair_type.php 3 "Срез болтов"
php add_repair_type.php 3 "Установка пластырей"
php add_repair_type.php 3 "Установка руля"
php add_repair_type.php 3 "Чистка диска"
php add_repair_type.php 3 "Чистка инжектора"
php add_repair_type.php 3 "Чистка регулятора холостого хода"
php add_repair_type.php 3 "Чистка форсунок"
php add_repair_type.php 3 "Шлифовка головки блока"
php add_repair_type.php 3 "Шлифовка коленвала"
php add_repair_type.php 3 "Шлифовка кольца осевого хождения коленчатого вала"
php add_repair_type.php 3 "Шприцевание кардана (замена смазки) 1 шт?"


php add_repair_post.php "Пост4"
php add_repair_type.php 4 "2013 Замена блока предохранителей"
php add_repair_type.php 4 "Балансировка колеса"
php add_repair_type.php 4 "Бортовка колеса"
php add_repair_type.php 4 "Диагностика автоэлектрики автомобиля"
php add_repair_type.php 4 "Диагностика двигателя"
php add_repair_type.php 4 "Диагностика на вибростенде"
php add_repair_type.php 4 "Забортовка колеса"
php add_repair_type.php 4 "Замена амортизаторов (иномарки)"
php add_repair_type.php 4 "Замена амортизаторов (отечеств)"
php add_repair_type.php 4 "Замена амортизаторов перед (отечеств)"
php add_repair_type.php 4 "Замена антифриза"
php add_repair_type.php 4 "Замена барабана (тормозного)"
php add_repair_type.php 4 "Замена бачка (расширительного)"
php add_repair_type.php 4 "Замена блока предохранителей"
php add_repair_type.php 4 "Замена Вакуумный усилитель"
php add_repair_type.php 4 "Замена Вал карданный рулевой УАЗ"
php add_repair_type.php 4 "Замена вентиля"
php add_repair_type.php 4 "Замена вкладышей (коренных)"
php add_repair_type.php 4 "Замена вкладышей (шатунных)"
php add_repair_type.php 4 "Замена втулок задней балки"
php add_repair_type.php 4 "Замена втулок рессорных"
php add_repair_type.php 4 "Замена втулок стабилизатора"
php add_repair_type.php 4 "Замена Втулок стабилизатора УАЗ"
php add_repair_type.php 4 "Замена генератора"
php add_repair_type.php 4 "Замена глушителя"
php add_repair_type.php 4 "Замена гранаты (шрус)"
php add_repair_type.php 4 "Замена ГРМ (ремни, ролики)"
php add_repair_type.php 4 "Замена датчика (все остальные)"
php add_repair_type.php 4 "Замена датчика положения дросельн. заслонки"
php add_repair_type.php 4 "Замена датчика положения распредвала"
php add_repair_type.php 4 "Замена датчика холостого хода"
php add_repair_type.php 4 "Замена дверных ручек"
php add_repair_type.php 4 "Замена заднего стабилизатора"
php add_repair_type.php 4 "Замена замка двери"
php add_repair_type.php 4 "Замена замка зажигания"
php add_repair_type.php 4 "Замена кардана (заднего) УАЗ"
php add_repair_type.php 4 "Замена кардана (переднего) УАЗ"
php add_repair_type.php 4 "Замена катушки зажигания"
php add_repair_type.php 4 "Замена клаппанов"
php add_repair_type.php 4 "Замена коллектора (выпускного)"
php add_repair_type.php 4 "Замена крестовины"
php add_repair_type.php 4 "Замена крестовины КПП"
php add_repair_type.php 4 "Замена кронштейна растяжки (краб)"
php add_repair_type.php 4 "замена масла в мостах"
php add_repair_type.php 4 "Замена масла в разд. кор."
php add_repair_type.php 4 "Замена масла ГУР"
php add_repair_type.php 4 "Замена масла ДВС"
php add_repair_type.php 4 "Замена масла КПП"
php add_repair_type.php 4 "Замена масла трансмисии"
php add_repair_type.php 4 "Замена мотора отопителя"
php add_repair_type.php 4 "Замена наконечников рулевых"
php add_repair_type.php 4 "Замена насоса маслянного"
php add_repair_type.php 4 "Замена опор стоек (перед)"
php add_repair_type.php 4 "Замена патрубка системы охлаждения"
php add_repair_type.php 4 "Замена платы фонаря (задн)"
php add_repair_type.php 4 "Замена подушки двигателя"
php add_repair_type.php 4 "Замена подшипника генератора (бол.)"
php add_repair_type.php 4 "Замена подшипника генератора (мал.)"
php add_repair_type.php 4 "Замена подшипника ступицы (задн.)"
php add_repair_type.php 4 "Замена подшипника ступицы (передн.)"
php add_repair_type.php 4 "Замена полуоси"
php add_repair_type.php 4 "Замена помпы (водяной насос)"
php add_repair_type.php 4 "Замена поршневой группы"
php add_repair_type.php 4 "Замена привода"
php add_repair_type.php 4 "Замена провода"
php add_repair_type.php 4 "Замена прокладки глушителя"
php add_repair_type.php 4 "Замена прокладки смотрового окна штанги"
php add_repair_type.php 4 "Замена пыльника гранаты (наружной)"
php add_repair_type.php 4 "Замена радиатора"
php add_repair_type.php 4 "Замена реактивных тяг"
php add_repair_type.php 4 "Замена регулятора тормозных сил"
php add_repair_type.php 4 "Замена резистора печки"
php add_repair_type.php 4 "Замена резонатора"
php add_repair_type.php 4 "Замена ремня / НЕ БРАТЬ"
php add_repair_type.php 4 "Замена ремня генератора"
php add_repair_type.php 4 "Замена ремня и роликов"
php add_repair_type.php 4 "Замена ремня ручейкового"
php add_repair_type.php 4 "Замена реостат переключателя печки"
php add_repair_type.php 4 "Замена ролика ГРМ (натяжного)"
php add_repair_type.php 4 "Замена рулевого кардана"
php add_repair_type.php 4 "Замена рулевой рейки"
php add_repair_type.php 4 "Замена рулевой трапеции"
php add_repair_type.php 4 "Замена рулевой тяги"
php add_repair_type.php 4 "Замена ручки двери"
php add_repair_type.php 4 "Замена рычага переключения передач"
php add_repair_type.php 4 "Замена рычага(нижнего)"
php add_repair_type.php 4 "Замена рычага(нижнего) косточка"
php add_repair_type.php 4 "Замена сайлентблоков"
php add_repair_type.php 4 "Замена сайлентблоков (отечеств)"
php add_repair_type.php 4 "Замена сайлентблоков перед (иномарки)"
php add_repair_type.php 4 "Замена сайлентблоков продольных тяг"
php add_repair_type.php 4 "Замена сальника коленвала (переднего)"
php add_repair_type.php 4 "Замена сальника КПП"
php add_repair_type.php 4 "Замена сальника полуоси"
php add_repair_type.php 4 "Замена сальника редуктора заднего моста"
php add_repair_type.php 4 "Замена сальников клаппанов"
php add_repair_type.php 4 "Замена свечей зажигания"
php add_repair_type.php 4 "Замена стартера"
php add_repair_type.php 4 "Замена стекла лобового"
php add_repair_type.php 4 "Замена стоек стабилизатора (линьки)"
php add_repair_type.php 4 "Замена ступицы (в сборе)"
php add_repair_type.php 4 "Замена сцепления"
php add_repair_type.php 4 "Замена термостата"
php add_repair_type.php 4 "Замена тормозного суппорта"
php add_repair_type.php 4 "Замена тормозной жидкости"
php add_repair_type.php 4 "Замена тормозных дисков"
php add_repair_type.php 4 "Замена тормозных колодок(дисковые)"
php add_repair_type.php 4 "Замена тормозных колодок(задних)"
php add_repair_type.php 4 "Замена тормозных колодок(пердних)"
php add_repair_type.php 4 "Замена тосола"
php add_repair_type.php 4 "Замена траверса КПП"
php add_repair_type.php 4 "Замена тросов ручного тормоза"
php add_repair_type.php 4 "Замена тяги в сборе (поперечная) УАЗ"
php add_repair_type.php 4 "Замена фильтра (воздушного)"
php add_repair_type.php 4 "Замена фильтра (салон)"
php add_repair_type.php 4 "Замена фильтра (тон.очистки)"
php add_repair_type.php 4 "Замена фильтра (топливного)"
php add_repair_type.php 4 "Замена фильтра АКПП"
php add_repair_type.php 4 "Замена фильтров"
php add_repair_type.php 4 "Замена форсунок"
php add_repair_type.php 4 "Замена цилиндра сцепления (главный)"
php add_repair_type.php 4 "Замена цилиндра сцепления (рабочий)"
php add_repair_type.php 4 "Замена цилиндра тормозного (главного)"
php add_repair_type.php 4 "Замена цилиндра тормозного (заднего)"
php add_repair_type.php 4 "Замена шаровой опоры"
php add_repair_type.php 4 "Замена шестерни зажигания (ведущей)"
php add_repair_type.php 4 "Замена шестерни распредвала"
php add_repair_type.php 4 "Замена шкворней"
php add_repair_type.php 4 "Замена шланга топливного"
php add_repair_type.php 4 "Замена шланга тормозного"
php add_repair_type.php 4 "Заправка кондиционера"
php add_repair_type.php 4 "Мойка автомобиля"
php add_repair_type.php 4 "Мойка блока двигателя"
php add_repair_type.php 4 "Мойка головки двигателя"
php add_repair_type.php 4 "Мойка колеса"
php add_repair_type.php 4 "Набивка коленвала"
php add_repair_type.php 4 "Осмотр ходовой"
php add_repair_type.php 4 "Перебортовка колеса"
php add_repair_type.php 4 "Подкачка колеса"
php add_repair_type.php 4 "Правка диска колеса"
php add_repair_type.php 4 "Притирка клаппанов"
php add_repair_type.php 4 "Проверка клаппанов"
php add_repair_type.php 4 "Промазка колеса"
php add_repair_type.php 4 "Промазка колеса герметиком"
php add_repair_type.php 4 "Разборка/Сборка ДВС"
php add_repair_type.php 4 "Разбортовка колеса"
php add_repair_type.php 4 "Развал-схождения"
php add_repair_type.php 4 "Райбирование направляющих клаппанов"
php add_repair_type.php 4 "Регулеровка ручного тормоза"
php add_repair_type.php 4 "Регулировка"
php add_repair_type.php 4 "Регулировка клапанов (в диагностике)"
php add_repair_type.php 4 "Регулировка рулевой рейки"
php add_repair_type.php 4 "Ремонт блока предохранителей"
php add_repair_type.php 4 "Ремонт генератора"
php add_repair_type.php 4 "Ремонт головки блока"
php add_repair_type.php 4 "Ремонт замка (центрального)"
php add_repair_type.php 4 "Ремонт камеры"
php add_repair_type.php 4 "Ремонт кронштейна крепления рулевой рейки"
php add_repair_type.php 4 "Ремонт МКПП (коробки передач)"
php add_repair_type.php 4 "Ремонт стеклоподъемника"
php add_repair_type.php 4 "Ремонт шины"
php add_repair_type.php 4 "Ремонт шины грибком"
php add_repair_type.php 4 "Ремонт шины пластырем R-19"
php add_repair_type.php 4 "Ремонт электропроводки"
php add_repair_type.php 4 "Сварка защиты картера"
php add_repair_type.php 4 "Снятие/Установка головки блока"
php add_repair_type.php 4 "Снятие/Установка ДВС"
php add_repair_type.php 4 "Снятие/Установка колеса"
php add_repair_type.php 4 "Срез болтов"
php add_repair_type.php 4 "Установка пластырей"
php add_repair_type.php 4 "Установка руля"
php add_repair_type.php 4 "Чистка диска"
php add_repair_type.php 4 "Чистка инжектора"
php add_repair_type.php 4 "Чистка регулятора холостого хода"
php add_repair_type.php 4 "Чистка форсунок"
php add_repair_type.php 4 "Шлифовка головки блока"
php add_repair_type.php 4 "Шлифовка коленвала"
php add_repair_type.php 4 "Шлифовка кольца осевого хождения коленчатого вала"
php add_repair_type.php 4 "Шприцевание кардана (замена смазки) 1 шт?"